kind: Service
apiVersion: v1
metadata:
  name: fastapi
  labels:
    app: openshift-sql-docker
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deployment: openshift-sql-docker

